POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3ZGMzNGY3ZjZmYmY5OGUwZTMyMmM1ZiIsImlhdCI6MTc0MjQ5ODMzMX0.pwQsWgkXsf1EGbrMA-F3-JBG6LRRXOUMIePks_O_lKk

{
    "title": "Adding jwt's implementation",
    "author": "Someone",
    "url": "https://example.com/blog/qwe",
    "likes": 3
}