services:
  react-app:
    image: todo-frontend
    build: 
      context: ./todo-frontend
      dockerfile: ./todo-frontend/Dockerfile
    volumes:
      - ./todo-frontend/dist:/usr/src/app
    container_name: todo-frontend-prod

  server:
    image: todo-backend
    build: 
      context: ./todo-backend
      dockerfile: ./todo-backend/Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
    container_name: todo-backend-prod
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo-prod

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: todo-reverse-proxy
    depends_on:
      - react-app
      - server

volumes:
  mongo_data:
  redis_data: